# Copyright 2024 The Knative Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-owner-references
  namespace: knative-restore
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-owner-references
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-controller-admin
subjects:
  - kind: ServiceAccount
    name: webhook-owner-references
    namespace: knative-restore
roleRef:
  kind: ClusterRole
  name: webhook-owner-references
  apiGroup: rbac.authorization.k8s.io
