# Copyright 2024 The Knative Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-owner-references
  namespace: knative-restore
  labels:
    app.kubernetes.io/component: webhook-owner-references
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-restore
spec:
  selector:
    matchLabels:
      app: webhook-owner-references
  template:
    metadata:
      labels:
        app: webhook-owner-references
        app.kubernetes.io/component: webhook-owner-references
        app.kubernetes.io/version: devel
        app.kubernetes.io/name: knative-serving
    spec:
      serviceAccountName: webhook-owner-references
      containers:
      - name: webhook
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: ko://github.com/dprotaso/webhook-owner-references/cmd/webhook

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault

        ports:
        - name: https-webhook
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook-owner-references
    app.kubernetes.io/component: webhook-owner-references
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-serving
  name: webhook-owner-references
  namespace: knative-restore
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: webhook-owner-references
